version: '3.4'
services:
  api-server:
    build:
      context: .
      dockerfile: ./build/APIserver/dev/Dockerfile
    container_name: api-server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - redis
    tty: true
    volumes:
      - "./APIserver/:/app"
  bff:
    build:
      context: .
      dockerfile: ./build/BFF/dev/Dockerfile
    container_name: bff
    restart: always
    ports:
      - 5000:5000
    volumes:
      - "./BFF/:/app"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - "./build/redis/data:/data"
