version: '3.4'
services:
  test-api-server:
    build:
      context: .
      dockerfile: ./build/APIserver/test/Dockerfile
    container_name: test-api-server
    ports:
      - 8080:8080
    depends_on:
      - test-redis
    tty: true
    volumes:
      - "./APIserver/:/app"
  #BFF:
    #
  test-redis:
    container_name: test-redis
    image: redis:latest
    ports:
      - 6379:6379
